# Generated by Django 2.2.2 on 2019-06-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myphone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usercode', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('deptname', models.CharField(max_length=30)),
                ('deptcode', models.CharField(max_length=30, null=True)),
                ('email', models.CharField(max_length=30, null=True)),
                ('phonenum', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='myuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usercode', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('deptname', models.CharField(max_length=30)),
                ('deptcode', models.CharField(max_length=30, null=True)),
                ('email', models.CharField(max_length=30, null=True)),
                ('phonenum', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tongxunlu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yuan', models.CharField(max_length=30)),
                ('xi', models.CharField(max_length=30)),
                ('zhuanye', models.CharField(max_length=30)),
                ('erjizhuanye', models.CharField(max_length=30, null=True)),
                ('xingming', models.CharField(max_length=30, null=True)),
                ('zhiwu', models.CharField(max_length=30, null=True)),
                ('zhize', models.CharField(max_length=500, null=True)),
                ('dianhua', models.CharField(max_length=30, null=True)),
                ('dizhi', models.CharField(max_length=30, null=True)),
                ('youxiang', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='yuan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('has_son', models.CharField(max_length=1, null=True)),
                ('has_father', models.CharField(max_length=1, null=True)),
                ('father_name', models.CharField(max_length=30, null=True)),
                ('son_name', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
